module.exports = [
  { images: [ 'fakeImageURL/63', 'fakeImageURL/263',  ],
    _id: '5e72b76620f46e318fe4c7e7',
    title: 'Treehouse of the Gods',
    size: '2 bedrooms',
    description: 'Dirt-nasty treehouse on top of a redwood tree.',
    price: 78,
    reviewScore: 32,
    reviewCount: 14,
    __v: 0 
  },
  { images: [ 'fakeImageURL/68', 'fakeImageURL/268' ],
    _id: '5e72b76620f46e318fe4c7ec',
    title: 'Josh Elder\'s World Famous Treehouse',
    size: '1 bedrooms',
    description: 'Large treehouse in my backyard.',
    price: 406,
    reviewScore: 17,
    reviewCount: 15,
    __v: 0 
  },
  { images: [ 'fakeImageURL/73', 'fakeImageURL/273' ],
    _id: '5e72b76620f46e318fe4c7f1',
    title: 'Fred Zirdung\'s Very Luxurious Treehouse',
    size: '5 bedrooms',
    description:
    'Ugly little treehouse in the middle of the desert, no food or water provided.',
    price: 227,
    reviewScore: 33,
    reviewCount: 18,
    __v: 0 
  },
  { images: [ 'fakeImageURL/78', 'fakeImageURL/278' ],
    _id: '5e72b76620f46e318fe4c7f6',
    title: 'Fred Zirdung\'s Very Luxurious Treehouse',
    size: '5 bedrooms',
    description: 'Disgusting treehouse in the middle of the woods.',
    price: 342,
    reviewScore: 31,
    reviewCount: 3,
    __v: 0 
  },
  { images: [ 'fakeImageURL/83', 'fakeImageURL/283' ],
    _id: '5e72b76620f46e318fe4c7fb',
    title: 'Marcus\'s Extremely Intense Treehouse',
    size: '3 bedrooms',
    description: 'Very stable treehouse in the middle of nowhere.',
    price: 321,
    reviewScore: 44,
    reviewCount: 8,
    __v: 0 
  },
  { images: [ 'fakeImageURL/88', 'fakeImageURL/288' ],
    _id: '5e72b76620f46e318fe4c800',
    title: 'Best Damn Treehouse On The Planet',
    size: '4 bedrooms',
    description:
    'Very stable treehouse to be shared with an old man named Clyde',
    price: 54,
    reviewScore: 5,
    reviewCount: 35,
    __v: 0 
  },
  { images: [ 'fakeImageURL/93', 'fakeImageURL/293' ],
    _id: '5e72b76620f46e318fe4c805',
    title: 'Marcus\'s Extremely Intense Treehouse',
    size: '4 bedrooms',
    description: 'Disgusting treehouse infested with interesting creatures.',
    price: 141,
    reviewScore: 6,
    reviewCount: 31,
    __v: 0 
  },
  { images: [ 'fakeImageURL/98', 'fakeImageURL/298' ],
    _id: '5e72b76620f46e318fe4c80a',
    title: 'Vinnie\'s Very Viewable Treehouse',
    size: '3 bedrooms',
    description: 'Large treehouse infested with interesting creatures.',
    price: 431,
    reviewScore: 17,
    reviewCount: 22,
    __v: 0 
  }
];